// ==========================================
// SEED TESTS 6-10 — Copy-paste into GAS Editor
// Run: seedTests06to10()
// ==========================================

function seedTests06to10() {
  var ss = SpreadsheetApp.openById('YOUR_SPREADSHEET_ID_HERE');
  var questionsSheet = ss.getSheetByName('Questions');

  function addQ(sheet, testId, questions) {
    questions.forEach(function(q, i) {
      var pn = (i < 4) ? 1 : (i < 16) ? 2 : (i < 28) ? 3 : 4;
      sheet.appendRow(['T'+testId+'_Q'+(i+1), testId, pn, q[0], q[1], q[2]||'', q[3]||'', q[4]||'', q[5]||'', q[6]||'', q[7], q[8]||0.25, q[9]||'']);
    });
  }

  // ==================== TEST 06 ====================
  addQ(questionsSheet, 6, [
    ['Pronunciation: -ed endings','A. exercised B. walked C. jogged D. breathed','','A. /d/','B. /t/','C. /d/','D. /d/','B',0.25],
    ['Pronunciation: Vowels','A. health B. meat C. meal D. clean','','A. /e/','B. /iː/','C. /iː/','D. /iː/','A',0.25],
    ['Word Stress: 2-syllable','A. diet B. perform C. fitness D. yoga','','A. diet(am1)','B. perform(am2)','C. fitness(am1)','D. yoga(am1)','B',0.25],
    ['Word Stress: 3-syllable','A. nutrition B. vegetable C. mineral D. vitamin','','A. nutrition(am2)','B. vegetable(am1)','C. mineral(am1)','D. vitamin(am1)','A',0.25],
    ['Vocabulary: Health','Eating too much fast food can lead to ____. A. health B. healthy C. obesity D. fit','','A. health','B. healthy','C. obesity','D. fit','C',0.25],
    ['Grammar: Modal Verbs','You ____ drink at least 2 liters of water every day. A. should B. may C. can D. will','','A. should','B. may','C. can','D. will','A',0.25],
    ['Phrasal Verbs','John decided to ____ smoking for his health. A. give up B. take up C. put up D. look up','','A. give up','B. take up','C. put up','D. look up','A',0.25],
    ['Prepositions','Exercise is good ____ your heart and lungs. A. at B. for C. in D. on','','A. at','B. for','C. in','D. on','B',0.25],
    ['Vocabulary: Nutrition','Fruits and vegetables are rich ____ vitamins. A. of B. for C. at D. in','','A. of','B. for','C. at','D. in','D',0.25],
    ['Grammar: Present Perfect','She ____ to the gym three times this week. A. went B. goes C. has gone D. has been','','A. went','B. goes','C. has gone','D. has been','D',0.25],
    ['Grammar: Comparison','The more you exercise, the ____ you become. A. healthy B. healthier C. healthiest D. more healthy','','A. healthy','B. healthier','C. healthiest','D. more healthy','B',0.25],
    ['Communication','Doctor: "What seems to be the problem?" Patient: "____" A. I have a headache. B. No problem. C. Thank you. D. You\'re welcome.','','A. I have a headache','B. No problem','C. Thank you','D. You\'re welcome','A',0.25],
    ['Communication','Friend: "You look great! Have you lost weight?" You: "____" A. Yes, I\'ve been exercising. B. No, I eat a lot. C. I don\'t know. D. That\'s too bad.','','A. Yes, exercising','B. No, I eat a lot','C. I don\'t know','D. That\'s too bad','A',0.25],
    ['Public Signs','Red cross sign → A. Church B. Hospital/medical help C. No crossing D. Plus sign','','A. Church','B. Medical help','C. No crossing','D. Plus sign','B',0.25],
    ['Public Signs','"No food or drink allowed" → A. Free food B. Restaurant C. Do not eat/drink here D. Picnic','','A. Free food','B. Restaurant','C. Do not eat/drink','D. Picnic','C',0.25],
    ['Grammar: Wish','I wish I ____ so much junk food yesterday. A. didn\'t eat B. hadn\'t eaten C. don\'t eat D. won\'t eat','','A. didn\'t eat','B. hadn\'t eaten','C. don\'t eat','D. won\'t eat','B',0.25],
    ['Cloze Test','A healthy lifestyle (17)____ regular exercise and a balanced diet. Experts recommend 150 minutes of moderate exercise (18)____ week. Eating a variety of foods (19)____ important. Drinking water helps the body (20)____ properly. Many find it hard to maintain habits (21)____ of busy schedules. Small changes like stairs instead (22)____ the elevator help.','','A. includes','B. including','C. include','D. included','A',0.25],
    ['Cloze Test','Fill (18): "150 minutes (18)____ week"','','A. a','B. per','C. for','D. in','A',0.25],
    ['Cloze Test','Fill (19): "eating foods (19)____ important"','','A. is','B. are','C. was','D. were','A',0.25],
    ['Cloze Test','Fill (20): "helps the body (20)____ properly"','','A. function','B. functioning','C. functions','D. functioned','A',0.25],
    ['Cloze Test','Fill (21): "maintain habits (21)____ of busy schedules"','','A. because','B. due','C. since','D. as','A',0.25],
    ['Cloze Test','Fill (22): "instead (22)____ the elevator"','','A. for','B. to','C. from','D. of','D',0.25],
    ['Reading','Sleep is as important as diet and exercise. During sleep, bodies repair and brains process information. Teenagers need 8-10 hours, but many get less due to homework and screens. Lack of sleep causes poor concentration, mood swings, and weak immunity. Experts recommend a regular schedule, avoiding screens before bed, and a calm sleeping environment. --- Q23: How much sleep do teens need? A. 5-6h B. 6-7h C. 8-10h D. 10-12h','','A. 5-6h','B. 6-7h','C. 8-10h','D. 10-12h','C',0.25],
    ['Reading: True/False','Q24: Sleep helps the body repair itself. A. TRUE B. FALSE','','A. TRUE','B. FALSE','','','A',0.25],
    ['Reading: True/False','Q25: Most teens get enough sleep. A. TRUE B. FALSE','','A. TRUE','B. FALSE','','','B',0.25],
    ['Reading: True/False','Q26: Lack of sleep can weaken immunity. A. TRUE B. FALSE','','A. TRUE','B. FALSE','','','A',0.25],
    ['Reading: MCQ','Q27: Best tip for better sleep? A. Use screens B. Calm environment C. Stay up late D. Drink coffee','','A. Use screens','B. Calm environment','C. Stay up late','D. Drink coffee','B',0.25],
    ['Reading: Main Idea','Q28: Main message? A. Study more B. Sleep is important C. Screens good D. Diet > sleep','','A. Study more','B. Sleep is important','C. Screens good','D. Diet > sleep','B',0.25],
    ['Word Form','Exercise improves both physical and ____ health. (MENTALITY)','','','','','','mental',0.25],
    ['Word Form','A ____ diet includes all nutrients you need. (BALANCE)','','','','','','balanced',0.25],
    ['Word Form','Smoking is ____ to your health. (HARM)','','','','','','harmful',0.25],
    ['Word Form','She went to the doctor because of a serious ____. (ILL)','','','','','','illness',0.25],
    ['Word Form','The doctor ____ that I should rest more. (SUGGESTION)','','','','','','suggested',0.25],
    ['Word Form','Eating ____ can lead to health problems. (HEALTHY)','','','','','','unhealthily',0.25],
    ['Dictionary Insertion','"recover /rɪˈkʌvər/ v: to return to normal health." It took two weeks to ____ from the flu.','','','','','','recover',0.25],
    ['Dictionary Insertion','"prevent /prɪˈvent/ v: to stop from happening." Exercise can help ____ many diseases.','','','','','','prevent',0.25],
    ['Sentence Transformation','You should exercise regularly. → You had ____ regularly.','','','','','','better exercise',0.25],
    ['Sentence Transformation','I regret eating so much fast food. → I wish I ____ so much fast food.','','','','','','hadn\'t eaten',0.25],
    ['Sentence Transformation','She started eating healthy 2 years ago. → She has ____ healthy food for 2 years.','','','','','','been eating',0.25],
    ['Sentence Transformation','People believe exercise is the best medicine. → Exercise ____ the best medicine.','','','','','','is believed to be',0.25]
  ]);

  // ==================== TEST 07 ====================
  addQ(questionsSheet, 7, [
    ['Pronunciation: -ed endings','A. crossed B. parked C. waited D. watched','','A. /t/','B. /t/','C. /ɪd/','D. /t/','C',0.25],
    ['Pronunciation: Vowels','A. road B. boat C. broad D. coat','','A. /əʊ/','B. /əʊ/','C. /ɔː/','D. /əʊ/','C',0.25],
    ['Word Stress: 2-syllable','A. traffic B. helmet C. obey D. safety','','A. traffic(am1)','B. helmet(am1)','C. obey(am2)','D. safety(am1)','C',0.25],
    ['Word Stress: 3-syllable','A. pedestrian B. accident C. vehicle D. dangerous','','A. pedestrian(am2)','B. accident(am1)','C. vehicle(am1)','D. dangerous(am1)','A',0.25],
    ['Vocabulary','Wear a ____ when riding a motorbike. A. helmet B. seatbelt C. cap D. mask','','A. helmet','B. seatbelt','C. cap','D. mask','A',0.25],
    ['Grammar: Must','Drivers ____ stop when the light is red. A. can B. may C. must D. will','','A. can','B. may','C. must','D. will','C',0.25],
    ['Phrasal Verbs','I ____ the bus at the station near school. A. get on B. get up C. get off D. get down','','A. get on','B. get up','C. get off','D. get down','A',0.25],
    ['Prepositions','Look ____ both sides before crossing. A. at B. for C. to D. in','','A. at','B. for','C. to','D. in','A',0.25],
    ['Vocabulary','Speeding is the main ____ of many accidents. A. reason B. cause C. effect D. result','','A. reason','B. cause','C. effect','D. result','B',0.25],
    ['Grammar: Passive','Traffic rules ____ by all road users. A. must follow B. must be followed C. must followed D. following','','A. must follow','B. must be followed','C. must followed','D. following','B',0.25],
    ['Grammar: Conditional 1','If you ____ too fast, you will get a ticket. A. drive B. drives C. drove D. will drive','','A. drive','B. drives','C. drove','D. will drive','A',0.25],
    ['Communication','Policeman: "Sir, you were driving too fast." Driver: "____" A. I\'m sorry, officer. B. Thank you. C. No, I don\'t. D. Good idea.','','A. Sorry officer','B. Thank you','C. No, I don\'t','D. Good idea','A',0.25],
    ['Communication','Passenger: "Does this bus go to Ben Thanh?" Driver: "____" A. Yes, hop on. B. No, I am not. C. Thank you. D. Fine.','','A. Yes, hop on','B. No, I am not','C. Thank you','D. Fine','A',0.25],
    ['Public Signs','Red circle with white bar → A. Stop B. No entry C. Go straight D. Turn left','','A. Stop','B. No entry','C. Go straight','D. Turn left','B',0.25],
    ['Public Signs','Triangle with pedestrian figure → A. Playground B. Walking C. Pedestrian crossing ahead D. No pedestrians','','A. Playground','B. Walking','C. Pedestrian crossing','D. No pedestrians','C',0.25],
    ['Grammar: Used to','People ____ travel by bicycle more before motorbikes. A. used to B. are used to C. get used to D. use','','A. used to','B. are used to','C. get used to','D. use','A',0.25],
    ['Cloze Test','Road safety is a major concern. Every day, (17)____ of people use roads. Accidents are common, (18)____ due to speeding and drunk driving. The government introduced stricter (19)____. Wearing a helmet is (20)____ for all riders. Schools provide road safety (21)____ to teach students to cross roads and ride (22)____.','','A. million','B. millions','C. hundreds','D. thousand','B',0.25],
    ['Cloze Test','Fill (18): "common, (18)____ due to speeding"','','A. main','B. most','C. mainly','D. more','C',0.25],
    ['Cloze Test','Fill (19): "stricter (19)____ to reduce accidents"','','A. laws','B. tickets','C. lights','D. jams','A',0.25],
    ['Cloze Test','Fill (20): "helmet is now (20)____"','','A. optional','B. mandatory','C. suggested','D. recommended','B',0.25],
    ['Cloze Test','Fill (21): "road safety (21)____ for students"','','A. educate','B. educated','C. education','D. educating','C',0.25],
    ['Cloze Test','Fill (22): "ride bicycles (22)____"','','A. safe','B. safely','C. safety','D. safer','B',0.25],
    ['Reading','HCMC has over 8 million motorbikes, making traffic congestion a daily challenge. To address this, the city is expanding public transportation. The first metro line connects Ben Thanh Market to Suoi Tien Park. More metro lines and BRT systems are planned. While motorbikes remain popular, better public transit may encourage people to leave their bikes at home. --- Q23: How many motorbikes in HCMC? A. 80M B. 8M C. 800K D. 80K','','A. 80M','B. 8M','C. 800K','D. 80K','B',0.25],
    ['Reading: True/False','Q24: Metro line 1 connects Ben Thanh to Suoi Tien. A. TRUE B. FALSE','','A. TRUE','B. FALSE','','','A',0.25],
    ['Reading: True/False','Q25: Motorbikes are no longer popular in HCMC. A. TRUE B. FALSE','','A. TRUE','B. FALSE','','','B',0.25],
    ['Reading: True/False','Q26: HCMC has no plans for more metro lines. A. TRUE B. FALSE','','A. TRUE','B. FALSE','','','B',0.25],
    ['Reading: MCQ','Q27: "Congestion" means: A. Clear roads B. Heavy traffic jams C. Smooth flow D. Empty streets','','A. Clear roads','B. Heavy traffic jams','C. Smooth flow','D. Empty streets','B',0.25],
    ['Reading: Main Idea','Q28: Main topic? A. How to drive B. Transportation challenges & solutions in HCMC C. Ben Thanh history D. Motorbike types','','A. How to drive','B. Transport in HCMC','C. Ben Thanh history','D. Motorbike types','B',0.25],
    ['Word Form','Drivers should always drive ____. (CARE)','','','','','','carefully',0.25],
    ['Word Form','Wearing a helmet is ____ for all riders. (COMPEL)','','','','','','compulsory',0.25],
    ['Word Form','The city has seen a significant ____ in traffic. (INCREASE)','','','','','','increase',0.25],
    ['Word Form','Many ____ occur from drunk driving. (DIE)','','','','','','deaths',0.25],
    ['Word Form','Public ____ is being improved city-wide. (TRANSPORT)','','','','','','transportation',0.25],
    ['Word Form','Fasten your seatbelt ____. (SECURE)','','','','','','securely',0.25],
    ['Dictionary Insertion','"obey /əˈbeɪ/ v: to act according to a rule." Road users must ____ traffic rules.','','','','','','obey',0.25],
    ['Dictionary Insertion','"signal /ˈsɪɡnəl/ n: a sign giving information." A red traffic ____ means stop.','','','','','','signal',0.25],
    ['Sentence Transformation','You must wear a helmet when riding. → Helmets ____ when riding.','','','','','','must be worn',0.25],
    ['Sentence Transformation','People should use public transport more. → Public transport ____ more.','','','','','','should be used',0.25],
    ['Sentence Transformation','Wear a helmet or you\'ll be fined. → Unless you ____ a helmet, you\'ll be fined.','','','','','','wear',0.25],
    ['Sentence Transformation','He drove too fast so he had an accident. → If he ____ too fast, he wouldn\'t have had an accident.','','','','','','hadn\'t driven',0.25]
  ]);

  // ==================== TEST 08 ====================
  addQ(questionsSheet, 8, [
    ['Pronunciation: -ed endings','A. reported B. suggested C. invited D. opened','','A. /ɪd/','B. /ɪd/','C. /ɪd/','D. /d/','D',0.25],
    ['Pronunciation: -s/-es','A. watches B. manages C. loves D. passes','','A. /ɪz/','B. /ɪz/','C. /z/','D. /ɪz/','C',0.25],
    ['Word Stress: 2-syllable','A. invite B. visit C. decide D. accept','','A. invite(am2)','B. visit(am1)','C. decide(am2)','D. accept(am2)','B',0.25],
    ['Word Stress: 3-syllable','A. important B. excellent C. elegant D. difficult','','A. important(am2)','B. excellent(am1)','C. elegant(am1)','D. difficult(am1)','A',0.25],
    ['Grammar: Passive','The new bridge ____ last year. A. built B. was built C. is built D. has built','','A. built','B. was built','C. is built','D. has built','B',0.25],
    ['Grammar: Reported Speech','She said that she ____ to London the following week. A. will go B. would go C. goes D. went','','A. will go','B. would go','C. goes','D. went','B',0.25],
    ['Grammar: Conditional 3','If she had studied harder, she ____ the exam. A. would pass B. would have passed C. will pass D. passes','','A. would pass','B. would have passed','C. will pass','D. passes','B',0.25],
    ['Phrasal Verbs','Firemen managed to ____ the fire in an hour. A. put out B. put on C. put off D. put up','','A. put out','B. put on','C. put off','D. put up','A',0.25],
    ['Grammar: Wish','I wish I ____ harder for the final test. A. studied B. had studied C. study D. will study','','A. studied','B. had studied','C. study','D. will study','B',0.25],
    ['Grammar: Relative Clause','The man ____ car was stolen called police. A. who B. which C. whose D. whom','','A. who','B. which','C. whose','D. whom','C',0.25],
    ['Grammar: Tag Question','She hasn\'t finished yet, ____? A. has she B. hasn\'t she C. does she D. doesn\'t she','','A. has she','B. hasn\'t she','C. does she','D. doesn\'t she','A',0.25],
    ['Communication','Student: "I got the highest score!" Friend: "____" A. Terrible! B. Well done! C. I don\'t believe. D. So what?','','A. Terrible','B. Well done','C. I don\'t believe','D. So what','B',0.25],
    ['Communication','Teacher: "Who knows the answer?" Student: "____" A. Yes, I do! B. No, I am not. C. Yes, I did. D. Yes, I was.','','A. Yes, I do','B. No, I am not','C. Yes, I did','D. Yes, I was','A',0.25],
    ['Public Signs','Open book icon → A. Bookstore B. Library C. Reading area D. School','','A. Bookstore','B. Library','C. Reading area','D. School','B',0.25],
    ['Public Signs','Triangle with exclamation mark → A. Good news B. Warning/Danger C. Info D. Speed up','','A. Good news','B. Warning/Danger','C. Info','D. Speed up','B',0.25],
    ['Grammar: Inversion','Not until he arrived ____ the truth. A. did he know B. he knew C. he did know D. knows he','','A. did he know','B. he knew','C. he did know','D. knows he','A',0.25],
    ['Cloze Test','Learning English is essential (17)____ today\'s world. English (18)____ spoken by millions. Students (19)____ practice all four skills. Many focus only (20)____ grammar. Watching movies and (21)____ songs helps listening. The key is practice and not (22)____ afraid of mistakes.','','A. in','B. on','C. at','D. for','A',0.25],
    ['Cloze Test','Fill (18): "English (18)____ spoken by millions"','','A. is','B. are','C. was','D. were','A',0.25],
    ['Cloze Test','Fill (19): "Students (19)____ practice all skills"','','A. must','B. can','C. should','D. would','C',0.25],
    ['Cloze Test','Fill (20): "focus only (20)____ grammar"','','A. at','B. for','C. in','D. on','D',0.25],
    ['Cloze Test','Fill (21): "(21)____ songs helps"','','A. listen','B. listening','C. listening to','D. listened','C',0.25],
    ['Cloze Test','Fill (22): "not (22)____ afraid of mistakes"','','A. be','B. been','C. being','D. is','C',0.25],
    ['Reading','Passive voice focuses on action, not the doer. "The cake was eaten" focuses on the cake. It uses "to be" + past participle: "is eaten" (present), "was eaten" (past), "will be eaten" (future). Active voice is clearer and preferred in most writing. --- Q23: When is passive used? A. Doer is important B. Action more important than doer C. Only in science D. Never','','A. Doer important','B. Action > doer','C. Only science','D. Never','B',0.25],
    ['Reading: True/False','Q24: Passive uses "to be" + past participle. A. TRUE B. FALSE','','A. TRUE','B. FALSE','','','A',0.25],
    ['Reading: True/False','Q25: "Will be eaten" is present passive. A. TRUE B. FALSE','','A. TRUE','B. FALSE','','','B',0.25],
    ['Reading: True/False','Q26: Active voice is preferred for clarity. A. TRUE B. FALSE','','A. TRUE','B. FALSE','','','A',0.25],
    ['Reading: MCQ','Q27: "The cake was eaten" focuses on: A. Who ate B. The cake C. Time D. Reason','','A. Who ate','B. The cake','C. Time','D. Reason','B',0.25],
    ['Reading: Main Idea','Q28: Main topic? A. Grammar history B. How to use passive voice C. Why grammar is hard D. English future','','A. Grammar history','B. Passive voice usage','C. Why grammar hard','D. English future','B',0.25],
    ['Word Form','The ____ of the school was completed. (BUILD)','','','','','','building',0.25],
    ['Word Form','She is a famous ____ of children\'s books. (WRITE)','','','','','','writer',0.25],
    ['Word Form','The explanation was ____ to everyone. (CLEARLY)','','','','','','clear',0.25],
    ['Word Form','He received an ____ to the conference. (INVITE)','','','','','','invitation',0.25],
    ['Word Form','The ____ of the project depends on teamwork. (SUCCEED)','','','','','','success',0.25],
    ['Word Form','She speaks English very ____. (FLUENT)','','','','','','fluently',0.25],
    ['Dictionary Insertion','"translate /trænsˈleɪt/ v: to express in another language." Can you ____ this to Vietnamese?','','','','','','translate',0.25],
    ['Dictionary Insertion','"pronounce /prəˈnaʊns/ v: to make the sound of a word." How do you ____ this word?','','','','','','pronounce',0.25],
    ['Sentence Transformation','"I am writing a letter," she said. → She said ____ a letter.','','','','','','she was writing',0.25],
    ['Sentence Transformation','They built this school in 2010. → This school ____ in 2010.','','','','','','was built',0.25],
    ['Sentence Transformation','He didn\'t study, so he failed. → If he had studied, he ____.','','','','','','would have passed',0.25],
    ['Sentence Transformation','People say English is easy. → English ____ easy.','','','','','','is said to be',0.25]
  ]);

  // ==================== TEST 09 ====================
  addQ(questionsSheet, 9, [
    ['Pronunciation: -ed endings','A. discovered B. invented C. explored D. observed','','A. /d/','B. /ɪd/','C. /d/','D. /d/','B',0.25],
    ['Pronunciation: Vowels','A. science B. scientist C. silent D. special','','A. /aɪ/','B. /aɪ/','C. /aɪ/','D. /e/','D',0.25],
    ['Word Stress: 2-syllable','A. invent B. create C. publish D. explore','','A. invent(am2)','B. create(am2)','C. publish(am1)','D. explore(am2)','C',0.25],
    ['Word Stress: 3-syllable','A. discovery B. scientist C. experiment D. impressive','','A. discovery(am2)','B. scientist(am1)','C. experiment(am2)','D. impressive(am2)','B',0.25],
    ['Vocabulary','Scientists make ____ to understand the world. A. experiments B. experience C. explanation D. expression','','A. experiments','B. experience','C. explanation','D. expression','A',0.25],
    ['Grammar: Past Simple','Marie Curie ____ radium in 1898. A. discovered B. discovers C. has discovered D. was discovered','','A. discovered','B. discovers','C. has discovered','D. was discovered','A',0.25],
    ['Phrasal Verbs','Scientists try to ____ how the brain works. A. carry out B. find out C. put out D. get out','','A. carry out','B. find out','C. put out','D. get out','B',0.25],
    ['Prepositions','Many discoveries were made ____ accident. A. by B. on C. in D. with','','A. by','B. on','C. in','D. with','A',0.25],
    ['Vocabulary','The team studies the ____ of climate change. A. effects B. affects C. defects D. infects','','A. effects','B. affects','C. defects','D. infects','A',0.25],
    ['Grammar: Passive','The light bulb ____ by Thomas Edison. A. invented B. was invented C. invents D. is invented','','A. invented','B. was invented','C. invents','D. is invented','B',0.25],
    ['Grammar: So...that','The experiment was ____ dangerous that they stopped. A. such B. so C. very D. too','','A. such','B. so','C. very','D. too','B',0.25],
    ['Communication','Friend: "What do you think about space exploration?" You: "____" A. Fascinating! B. No, it doesn\'t. C. I don\'t know neither. D. For sure not.','','A. Fascinating','B. No, it doesn\'t','C. I don\'t know neither','D. For sure not','A',0.25],
    ['Communication','Teacher: "Who knows?" Student: "____" A. I think gravity. B. I don\'t. C. No answer. D. What question?','','A. I think gravity','B. I don\'t','C. No answer','D. What question','A',0.25],
    ['Public Signs','Microscope icon → A. Hospital B. Science lab/research C. Pharmacy D. School','','A. Hospital','B. Science lab','C. Pharmacy','D. School','B',0.25],
    ['Public Signs','Radiation symbol → A. Safe B. Caution: radiation C. Hospital D. Clean room','','A. Safe','B. Caution: radiation','C. Hospital','D. Clean room','B',0.25],
    ['Grammar: Future','Scientists believe humans ____ on Mars one day. A. will live B. live C. lived D. would live','','A. will live','B. live','C. lived','D. would live','A',0.25],
    ['Cloze Test','Newton is regarded (17)____ one of the greatest scientists. Born in 1643, (18)____ most famous work is gravity theory. An apple (19)____ on his head, making him question why objects fall. He developed laws of motion, laying the foundation (20)____ modern physics. He said "If I have seen further, it is (21)____ standing on giants\' shoulders," showing (22)____ for earlier scientists.','','A. as','B. like','C. for','D. with','A',0.25],
    ['Cloze Test','Fill (18): "(18)____ most famous work"','','A. He','B. Him','C. His','D. Her','C',0.25],
    ['Cloze Test','Fill (19): "apple (19)____ on his head"','','A. fall','B. falls','C. fell','D. fallen','C',0.25],
    ['Cloze Test','Fill (20): "foundation (20)____ modern physics"','','A. for','B. of','C. to','D. in','A',0.25],
    ['Cloze Test','Fill (21): "it is (21)____ standing on giants\' shoulders"','','A. through','B. by','C. with','D. in','B',0.25],
    ['Cloze Test','Fill (22): "showing (22)____ for earlier scientists"','','A. respect','B. respects','C. respected','D. respecting','A',0.25],
    ['Reading','Space exploration has advanced since the 1969 Moon landing. NASA, ESA, and SpaceX work on Mars missions. Mars is the most Earth-like planet, and evidence suggests it once had water. Challenges include a 7-month journey, radiation exposure, and limited supplies. Despite this, experts believe a manned Mars mission will happen within 20 years. --- Q23: First Moon landing year? A. 1959 B. 1969 C. 1979 D. 1989','','A. 1959','B. 1969','C. 1979','D. 1989','B',0.25],
    ['Reading: True/False','Q24: Mars is the most Earth-like planet. A. TRUE B. FALSE','','A. TRUE','B. FALSE','','','A',0.25],
    ['Reading: True/False','Q25: Journey to Mars takes 1 month. A. TRUE B. FALSE','','A. TRUE','B. FALSE','','','B',0.25],
    ['Reading: True/False','Q26: Mars never had water. A. TRUE B. FALSE','','A. TRUE','B. FALSE','','','B',0.25],
    ['Reading: MCQ','Q27: "Enormous" means: A. Very small B. Very large C. Interesting D. Simple','','A. Very small','B. Very large','C. Interesting','D. Simple','B',0.25],
    ['Reading: Main Idea','Q28: Main topic? A. Life on Mars B. Space exploration & Mars mission C. Apollo landing D. SpaceX history','','A. Life on Mars','B. Space & Mars mission','C. Apollo landing','D. SpaceX history','B',0.25],
    ['Word Form','Marie Curie made important ____ to science. (CONTRIBUTE)','','','','','','contributions',0.25],
    ['Word Form','The ____ of gravity changed our understanding. (DISCOVER)','','','','','','discovery',0.25],
    ['Word Form','Space is an ____ field with opportunities. (EXPLORE)','','','','','','exploratory',0.25],
    ['Word Form','Scientists need to be very ____. (PRECISION)','','','','','','precise',0.25],
    ['Word Form','The experiment was a complete ____. (FAIL)','','','','','','failure',0.25],
    ['Word Form','This is ____ important for future research. (SCIENCE)','','','','','','scientifically',0.25],
    ['Dictionary Insertion','"observe /əbˈzɜːv/ v: to watch for scientific purposes." Scientists ____ animal behavior.','','','','','','observe',0.25],
    ['Dictionary Insertion','"theory /ˈθɪəri/ n: formal ideas to explain something." Einstein\'s ____ of relativity.','','','','','','theory',0.25],
    ['Sentence Transformation','Scientists discovered a new planet. → A new planet ____ by scientists.','','','','','','has been discovered',0.25],
    ['Sentence Transformation','Newton discovered gravity. → It ____ who discovered gravity.','','','','','','was Newton',0.25],
    ['Sentence Transformation','Jupiter is the biggest planet. → No planet is ____ Jupiter.','','','','','','as big as',0.25],
    ['Sentence Transformation','They will send a robot to Mars. → A robot ____ to Mars.','','','','','','will be sent',0.25]
  ]);

  // ==================== TEST 10 ====================
  addQ(questionsSheet, 10, [
    ['Pronunciation: -s/-es','A. guitars B. pianos C. violins D. flutes','','A. /z/','B. /z/','C. /z/','D. /s/','D',0.25],
    ['Pronunciation: Vowels','A. music B. tune C. instrument D. sound','','A. /juː/','B. /juː/','C. /ɪ/','D. /aʊ/','D',0.25],
    ['Word Stress: 2-syllable','A. perform B. concert C. singer D. album','','A. perform(am2)','B. concert(am1)','C. singer(am1)','D. album(am1)','A',0.25],
    ['Word Stress: 3-syllable','A. musician B. festival C. instrument D. classical','','A. musician(am2)','B. festival(am1)','C. instrument(am1)','D. classical(am1)','A',0.25],
    ['Vocabulary','She plays the ____ in the school band. A. guitar B. football C. camera D. bicycle','','A. guitar','B. football','C. camera','D. bicycle','A',0.25],
    ['Grammar: Present Continuous','Listen! The band ____ on stage now. A. performs B. is performing C. performed D. has performed','','A. performs','B. is performing','C. performed','D. has performed','B',0.25],
    ['Phrasal Verbs','The concert was ____ due to bad weather. A. called off B. called up C. called on D. called for','','A. called off','B. called up','C. called on','D. called for','A',0.25],
    ['Prepositions','He is really interested ____ classical music. A. at B. in C. on D. for','','A. at','B. in','C. on','D. for','B',0.25],
    ['Vocabulary','The movie was so ____ that I fell asleep. A. exciting B. interesting C. boring D. amazing','','A. exciting','B. interesting','C. boring','D. amazing','C',0.25],
    ['Grammar: Gerund','She enjoys ____ to pop music while studying. A. listen B. to listen C. listening D. listened','','A. listen','B. to listen','C. listening','D. listened','C',0.25],
    ['Grammar: Comparison','This song is ____ than their last one. A. popular B. more popular C. most popular D. popularly','','A. popular','B. more popular','C. most popular','D. popularly','B',0.25],
    ['Communication','Ticket seller: "How many tickets?" Customer: "____" A. Two, please. B. Yes, I would. C. No problem. D. I like concerts.','','A. Two, please','B. Yes, I would','C. No problem','D. I like concerts','A',0.25],
    ['Communication','Friend: "What music do you like?" You: "____" A. I love K-pop! B. No, music. C. I listening music. D. Music good.','','A. I love K-pop','B. No, music','C. I listening','D. Music good','A',0.25],
    ['Public Signs','Musical note with a line through → A. Music store B. Silence/No loud music C. Concert hall D. Free lessons','','A. Music store','B. Silence/No loud music','C. Concert hall','D. Free lessons','B',0.25],
    ['Public Signs','Movie camera icon → A. Photos allowed B. Filming in progress C. Camera shop D. No cameras','','A. Photos allowed','B. Filming in progress','C. Camera shop','D. No cameras','B',0.25],
    ['Grammar: Wish','I wish I ____ play a musical instrument. A. can B. could C. will D. may','','A. can','B. could','C. will','D. may','B',0.25],
    ['Cloze Test','Music is a universal language connecting different (17)____. It reduces stress, improves mood, and (18)____ helps memory. Students find instrumental music helps (19)____ studying. Learning instruments develops discipline. Music students tend (20)____ better in school, especially (21)____ math and science. Music enriches our (22)____ in countless ways.','','A. cultures','B. countries','C. nations','D. cities','A',0.25],
    ['Cloze Test','Fill (18): "and (18)____ helps memory"','','A. too','B. also','C. even','D. either','C',0.25],
    ['Cloze Test','Fill (19): "helps concentration (19)____ studying"','','A. when','B. during','C. while','D. after','C',0.25],
    ['Cloze Test','Fill (20): "tend (20)____ better"','','A. to do','B. doing','C. do','D. did','A',0.25],
    ['Cloze Test','Fill (21): "especially (21)____ math"','','A. on','B. at','C. for','D. in','D',0.25],
    ['Cloze Test','Fill (22): "enriches our (22)____"','','A. life','B. lives','C. live','D. living','B',0.25],
    ['Reading','K-pop has become a global phenomenon. Groups like BTS and BLACKPINK have millions of fans worldwide. K-pop combines pop, hip-hop, R&B, and EDM. Social media like YouTube and TikTok helped spread it globally. Fans actively promote groups online, creating community. K-pop also contributes significantly to South Korea\'s economy. --- Q23: K-pop stands for? A. Korean pop B. King pop C. Karaoke pop D. Kids pop','','A. Korean pop','B. King pop','C. Karaoke pop','D. Kids pop','A',0.25],
    ['Reading: True/False','Q24: BTS fans are called "BLINK". A. TRUE B. FALSE','','A. TRUE','B. FALSE','','','B',0.25],
    ['Reading: True/False','Q25: K-pop combines multiple genres. A. TRUE B. FALSE','','A. TRUE','B. FALSE','','','A',0.25],
    ['Reading: True/False','Q26: Social media helped spread K-pop. A. TRUE B. FALSE','','A. TRUE','B. FALSE','','','A',0.25],
    ['Reading: MCQ','Q27: "Catchy" means: A. Hard to understand B. Easy to remember C. Very slow D. Extremely loud','','A. Hard to understand','B. Easy to remember','C. Very slow','D. Extremely loud','B',0.25],
    ['Reading: Main Idea','Q28: Main topic? A. How to sing B. K-pop success and characteristics C. Korean economy D. Social media','','A. How to sing','B. K-pop success','C. Korean economy','D. Social media','B',0.25],
    ['Word Form','She has a beautiful ____. (SING)','','','','','','voice',0.25],
    ['Word Form','The ____ gave an amazing performance. (MUSIC)','','','','','','musician',0.25],
    ['Word Form','The movie received mixed ____. (REVIEW)','','','','','','reviews',0.25],
    ['Word Form','Children are very ____. (CREATE)','','','','','','creative',0.25],
    ['Word Form','The concert was ____ successful. (INCREDIBLE)','','','','','','incredibly',0.25],
    ['Word Form','Music is a source of ____. (INSPIRE)','','','','','','inspiration',0.25],
    ['Dictionary Insertion','"perform /pəˈfɔːm/ v: to entertain by singing or dancing." The band will ____ live tonight.','','','','','','perform',0.25],
    ['Dictionary Insertion','"audience /ˈɔːdiəns/ n: people watching a performance." The ____ clapped loudly.','','','','','','audience',0.25],
    ['Sentence Transformation','She sings beautifully. → She is ____ singer.','','','','','','a beautiful',0.25],
    ['Sentence Transformation','The concert was exciting; everyone cheered. → It was ____ exciting concert.','','','','','','such an',0.25],
    ['Sentence Transformation','I prefer pop to classical. → I like pop ____ classical.','','','','','','better than',0.25],
    ['Sentence Transformation','They cancelled the concert due to rain. → The concert ____ due to rain.','','','','','','was cancelled',0.25]
  ]);

  Logger.log('Tests 6-10 seeded. Continue with tests 11-25.');
}
